### ISSUE TITLE
how it can support sourcemap for third party libarary installed `node_modules`

### ISSUE THREAD

**Issue by tianyingchun** [belgattitude/nextjs-monorepo-example#1267]
i tried install thrid party libarary in node-modules, in next app, import `function`  from `node_modules` it seems it could not load source map file in chrome, e.g. i. have module file `is-null.js` & `is-null.js.map` the `is-null.js.map` indicates the source `ts` file.

but it can not display `is-null.ts` in chrome `sources` panel. is there missed some configuratins?

i also create issue in next.js https://github.com/vercel/next.js/issues/34026

**Comment by belgattitude** [comment]
Hey @tianyingchun Is it linked to monorepo structure or more a general nextjs question ?

In this example repository I don't really take time to support applications, just gathering some tips for people using monorepo/workspaces. Scope is quite limited

Let me know, if you think it relates to the monorepo. Just give some more info. 

I'll try to help

**Comment by tianyingchun** [comment]
thanks a lot , it seems that i have find why, it should be issue of `next-transpile-modules` if we remove `next-transpile-modules` the source map works fine, if use `withTM` plugin it will convert `esm` into `cjs` will lose original source map.

**Comment by belgattitude** [comment]
Make sense. 

Now that nextjs supports `experimental.externalDir`, I tend to avoid using next-transpile-modules if not required.

this doc can help https://github.com/belgattitude/nextjs-monorepo-example/blob/main/README.md#step-33-next-config

**Comment by belgattitude** [comment]
I'll close the issue.

**Comment by tianyingchun** [comment]
yes, i have tried externalDir it seems that it not perfect, if we put styles into `packages/core`, it will broken or more configurations

**Comment by belgattitude** [comment]
Nice, yes it does not work in all cases.

Some tips in this thread: https://github.com/vercel/next.js/discussions/26420

Otherwise create an issue in next-transpile-modules... But I feel what you're looking for is difficult to achieve right now.
