### ISSUE TITLE
Disabled SWC as replacement for Babel

### ISSUE THREAD

**Issue by picosam** [belgattitude/nextjs-monorepo-example#1535]
Hello! I believe you're aware of this, so I guess this is more like a question. When I try to build the Next.js app, I get the following warning:

```
Process started
info  - Checking validity of types...
info  - Creating an optimized production build...
info  - Disabled SWC as replacement for Babel because of custom Babel configuration "babel.config.js" https://nextjs.org/docs/messages/swc-disabled
info  - Using external babel configuration from /Users/.../web-app/babel.config.js
Compiled successfully
```

May you please why we need a specific Babel configuration and if it's worth to forego SWC for it?

**Comment by belgattitude** [comment]
emotion is not yes fully supported without babel. Just need a bit of time. 

But feel free to adapt.

**Comment by belgattitude** [comment]
@picosam latest news about swc.

- The `swcMinify: true` starts to become stable with pretty much every library I throw on it and gives pretty much the same size gains than terser with a little speed gain.
- Using swc with emotion is still a bit young. It doesn't work with some libs I tried and while emotion support is experimental, it seems to work fine for simple scenarios. The bundle size is a bit bigger (it does not read browserlist, so it emits es5 for now) and the speed is passing from 35s to 30secs for the nextjs-app example. Not a lot (see https://github.com/belgattitude/nextjs-monorepo-example/pull/1850)

**Comment by belgattitude** [comment]
@picosam 

Nextjs 12.2 brought improvements (css-in-js/emotion supported out of the box). Not sure it's totally stable

But I will merge https://github.com/belgattitude/nextjs-monorepo-example/pull/2187 this soon. 

Had to increase slightly the browser size-limit checks (few extra Kb's)
