### ISSUE TITLE
Why add to emotionStyleTags in _document.tsx?

### ISSUE THREAD

**Issue by picosam** [belgattitude/nextjs-monorepo-example#1540]
Hello, may I ask, in why this is required here: https://github.com/belgattitude/nextjs-monorepo-example/blob/c700258def74f75b22bb9db5c01ecd46ff963047/apps/web-app/src/pages/_document.tsx#L53

**Comment by belgattitude** [comment]
It's to inline css in the hydrated html (aka critical path extraction if I'm not wrong)

You can check the result by looking at the raw html on the example page. It will help the browser to render elements faster as the styles are inlined.

There's pros and cons of this method.  If you're not working with css in js or simply care less about server side renderer you can completely opt out by deleting document.tsx

BTW take the examples with a pinch of salt I actually haven't put energy in there.  It's more a collection of tips and tricks to design a monorepo

**Comment by belgattitude** [comment]
I read a bit too fast, I realized you probably know about the inlining. The question remains open,  il check for a use case

**Comment by belgattitude** [comment]
Hey @picosam sorry for delay... The `ReactChildren.toArray(initialProps.styles)` is to not overwrite eventual styles that might have been added in the head section. Might also allow to use styled-jsx but I'm not so sure how they work internally.

But there's a good news... The critical path extraction seems to work natively, so those hacky things have been removed in the latest example: https://github.com/belgattitude/nextjs-monorepo-example/pull/1744. 

I've tested it on another project and so far it works pretty well. The old implementation might be useful if you're relying on multiple cache instances...

I'll close feel free to re-open whenever
