### ISSUE TITLE
Using ts-jest/babel-jest with this setup

### ISSUE THREAD

**Issue by lucas-janon** [belgattitude/nextjs-monorepo-example#18]
Hi! I'm using this setup in our monorepo and it's awesome, having cross-package fast refresh and being able to import external packages without building/watching them really makes the difference in DX.

I've been trying to set Jest for the whole morning with no success, so I'll like to ask you for some hints if you already did it.

So far, I was able to use the tsconfig to resolve packages paths:

```js
module.exports = {
  // ...config
  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, {
    prefix: "<rootDir>/../../../",
  }),
  // ...more config
};
```

But got this error while importing them:

![image](https://user-images.githubusercontent.com/7400784/102242387-c130f000-3ed8-11eb-9a25-449e2ee33391.png)

I tried both ts-jest and babel-jest and couldn't make them work.

I think this may have to do with Jest not being "aware" of the need to transpile the monorepo packages, since that's not specified neither in .babelrc nor tsconfig.json.

Is there any way to make Jest transpile monorepo packages?

Thanks

**Comment by belgattitude** [comment]
Nice question, of couse I have an answer. A nice one, But I'll you tomorrow ;) Cause now time for freedom !

**Comment by lucas-janon** [comment]
Enjoy 🙌

Talk tomorrow!

**Comment by belgattitude** [comment]
Yo I'm about to create a P/R :) But work will fill my day. I give you two hints in the meantime:

1. For tsconfig-path

It's a bit like you've illustrated with ts-jest:

```js
module.exports = {
  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, {
    prefix: "<rootDir>/../../../",
  }),
  // But here add an create a specific tsconfig.jest.json
  globals: {
    'ts-jest': {
      diagnostics: true,
      tsconfig: './tsconfig.jest.json',
    },
  },
};
```

The new `tsconfig.jest.json` could something something like

```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
  }
}
```

The important part being: target and module...

This should work



2. For next-transpile-modules

It's gonna be a bit more complicated, cause you'll need to set yourself the moduleNameMapper...


Once I have a free slot, I'll add a P/R :smile: 

Hope it helps

**Comment by lucas-janon** [comment]
Thanks! I did a quick test and got this error:
![image](https://user-images.githubusercontent.com/7400784/102498360-a1c0d100-4058-11eb-8632-be70bd829ec6.png)

Tried setting `"jsx": "react"` in tsconfig.test.json and `babelConfig: ".babelrc"` in jest.config.js with no success.

I'll try a few more things soon and let you know.

Thanks for the answer!

**Comment by belgattitude** [comment]
Hey @lucas-janon, here's a working config: https://github.com/belgattitude/vercel-monorepo-test/pull/20

Heppy new year !
