### ISSUE TITLE
Early cache invalidation in multistage Docker build 

### ISSUE THREAD

**Issue by afreemanio** [belgattitude/nextjs-monorepo-example#1867]
Hello - I'm not sure if this counts more as a question or an issue, as I am not sure if this is intentional or not.
So essentially, when running docker compose to build this project, if there is a change in any of the workspace files, an early build step is rerun, and the cache for all subsequent docker commands is also invalidated for some reason. 

For example (from a fresh install):

- Run `docker compose -f docker-compose.nextjs-app.yml build runner`
- The cache has not yet been built, so this takes around 180 seconds to build on my machine
- Run `docker compose -f docker-compose.nextjs-app.yml build runner` again
- The cache has been built and no files have changed, so the build takes basically no time to finish (as it should)
- In apps\nextjs-app\src\pages\_app.tsx, add a single character to the comment on line 45 ( `* Generally don't enable getInitialProp if you don't need to,` ->  `* Generally, don't enable getInitialProp if you don't need to.`)
- Run `docker compose -f docker-compose.nextjs-app.yml build runner` again
- In the first build stage (deps [7/7]), the `yarn install --immutable --inline-builds` command runs again, and takes 60 seconds to finish (specifically, jumping straight to the yarn 'link step'), and all subsequent commands in all following stages (builder and runner) are no longer cached.

This also occurs when the deps or builder stages are built only (ex. `docker compose -f docker-compose.nextjs-app.yml build deps`)

This is especially an issue in situations where one would want to create multiple builders/runners for different applications within the same dockerfile, as the 'deps' stage and all further stages would have to be rebuilt after every single change made throughout any of the packages/apps (even though none of the dependencies actually change).

This issue is currently affecting the most recent commit (3952f1603b1bc87eab0c5e1e92b5640cdddacab7) but also affects all of the previous versions I have tested up until now.

**Comment by belgattitude** [comment]
I haven't updated the dockerfile since a while and use a different one in prod. I'll see what I can I do next week. I'm open to ideas as well cause I reprends trying a lot of things

Thanks for reporting

**Comment by belgattitude** [comment]
I completely forgot.  Have you tried with DOCKER_BUILDKIT=1 ?

**Comment by afreemanio** [comment]
Thank you for your response. The example given above was done running with when running the above example on Docker version 20.10.17, build 100c701, with buildkit enabled. I can confirm this happens when running docker on Ubuntu 20.04.4 LTS x86_64, as well as on Docker Desktop for Windows using the WSL2 backend. When I manually disable buildkit, I get the following error:
```
1 error occurred:
        * Status: the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled, Code: 1
```

**Comment by belgattitude** [comment]
Closing as docker example was reworked recently. Thx
