### ISSUE TITLE
How debug server side for next.js `nextjs-app` using vscode?

### ISSUE THREAD

**Issue by tianyingchun** [belgattitude/nextjs-monorepo-example#2317]
it seems that for mono no way to debug server side of `nextjs-app`?

**Comment by belgattitude** [comment]
I guess there is.

Did you try first https://nextjs.org/docs/advanced-features/debugging#server-side-code ?

I guess after that you just add configuration to vscode workspace. 

Let me know,  cause I'm not using vscode myself

**Comment by tianyingchun** [comment]
yes from next.js.org/doc only below can works
```
- cd /apps/app-next
- yarn dev
- open chrome: `chrome://inspect`
```
we must using chrome browser, it seems that it won't works directly use vscode, i don't know why.

**Comment by belgattitude** [comment]
Open an issue in nextjs or vscode. 

I feel this one is out of scope for me 😄
