### ISSUE TITLE
Adding commitzen command

### ISSUE THREAD

**Issue by Enjoy2Live** [belgattitude/nextjs-monorepo-example#2420]
Hi @belgattitude and thank you very much for this template, with it I was able to bootstrap a monorepo for our organization very quickly.

One tiny suggestion: I think having a commit linter only can be a bit frustrating without an interface to teach a contributor the commit convention used.
I've previously used [commitzen](https://commitizen-tools.github.io/commitizen/) which works as a [vscode extension](https://marketplace.visualstudio.com/items?itemName=KnisterPeter.vscode-commitizen) and npm package and I think with a bit of tweaking to make it aligned with the commit linter this would be a good feature added to this amazing template.

**Comment by belgattitude** [comment]
Sounds a lovely idea. 

From experience I realized it can be useful when introducing the conventional commits in a team. I agree with you.

I'll see what I can do

**Comment by belgattitude** [comment]
Forgot to comment here.  But I've reverted some attempt https://github.com/belgattitude/nextjs-monorepo-example/pull/2784. Good tool but more maintenance and not working everywhere.
