### ISSUE TITLE
How to use `baseUrl` in `bar` package

### ISSUE THREAD

**Issue by andreavaccari** [belgattitude/nextjs-monorepo-example#27]
Hi @belgattitude. Thank you for sharing this monorepo, it's been very helpful.

I'm trying to accomplish a similar setup for a new project. In particular, I'm setting up a monorepo with two Next.js apps and several private packages for things like UI components and domain logic. I'm trying to exclusively use the `tsconfig.paths` approach and avoid the `next-transpile-module` approach.

My question is: is it possible, and, if so, is it appropriate, to use `baseUrl` in my private packages? For example, I cloned your repo, added `baseUrl` to `bar`'s `tsconfig`, and changed one import to non-absolute. VS code can find the module and does not complain, but when I run the `web-app` I get a "module not found" error.

See: https://github.com/belgattitude/nextjs-monorepo-example/compare/master...andreavaccari:av/non-relative-imports

Is it wrong to use `baseUrl` in this situation?

**Comment by belgattitude** [comment]
I'm off few days 😄 so I can't really give you an answer. 

But first thought,  prefer working with next-transpile-modules for now. 

The support for baseUrl was not yet prime time with tsconfig paths. See also https://github.com/vercel/next.js/discussions/15327 but I know latest versions of typescript may have changed the game.

That said if you find a solution let me know cause it would be awesome.

**Comment by belgattitude** [comment]
@andreavaccari remember now, the support for basePath should land in nextjs first.

Nextjs translates the tsconfig.json with limited support right now (yep it actually uses babel)... You can always trick this in the nextjs.config, by hardcoding the modules you want. Don't have a solution in mind right now, but I feel it should be possible

**Comment by andreavaccari** [comment]
Hi @belgattitude Thank you for your help on this. We ended up going with `nx` for the monorepo.
