### ISSUE TITLE
Does it support NodeNext .mjs, .mts ?

### ISSUE THREAD

**Issue by tianyingchun** [belgattitude/nextjs-monorepo-example#2763]
Does it support NodeNext .mjs, .mts ?

https://www.typescriptlang.org/docs/handbook/esm-node.html

**Comment by belgattitude** [comment]
I would say better to try to see :) But imho is too early. Not sure all frameworks plays well with it.

**Comment by tianyingchun** [comment]
sure, but we can at the same support `require` & `import` via `exports` of package.json

**Comment by tianyingchun** [comment]
BTW : Is there a mistake here? https://github.com/belgattitude/nextjs-monorepo-example/blob/main/packages/eslint-config-bases/package.json#L17
``` json
 "main": "./index.js",
 ```
 
 or
 
 ``` json
 "main": "./src/index.js",
 ```

**Comment by belgattitude** [comment]
Yes totally.  Can you make a pr ?

**Comment by belgattitude** [comment]
Top

**Comment by tianyingchun** [comment]
@belgattitude 
how about command `yarn check:install` can this command allow ignore `project`?  where is the document for this command 

thanks.

**Comment by belgattitude** [comment]
Currently `check:install` is calling [yarn doctor](https://www.npmjs.com/package/@yarnpkg/doctor). Unfortunately there's a bug if you're on latest 4rc, so use the latest 3.x version instead: https://github.com/yarnpkg/berry/issues/5033.

The idea here is to have a quick check about "ghost" deps (also missing peer-deps), but you use other scripts as well, ie: https://github.com/sverweij/dependency-cruiser...
