### ISSUE TITLE
Example with standalone build

### ISSUE THREAD

**Issue by iacobfred** [belgattitude/nextjs-monorepo-example#2785]
Hi, this is a great repo and has been really helpful to me in setting up my own Next.js monorepo. Thank you.

One suggestion. Next.js recommends using output file tracing ("standalone" build) with Docker:
- https://nextjs.org/docs/advanced-features/output-file-tracing
- https://github.com/vercel/next.js/tree/canary/examples/with-docker

I've modified your example to use this feature, and it seems to work. 

In `next.config.mjs`:

```
import path from "path";
import url from "url";

const _filename_ = url.fileURLToPath(import.meta.url);
const _dirname_ = path.dirname(_filename_);
const ROOT_DIR = path.resolve(_dirname_, "..", "..");

/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
  ...
  experimental: {
    // For tracing, include files from the monorepo base (two directories up).
    // https://nextjs.org/docs/advanced-features/output-file-tracing#caveats
    outputFileTracingRoot: ROOT_DIR,
  },
  output: "standalone",
  ...
};
```

In Dockerfile's last stage:
```
ARG APP_NAME

WORKDIR /base/apps/${APP_NAME}

ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /base/apps/${APP_NAME}/.next/standalone/ /base/
COPY --from=builder --chown=nextjs:nodejs /base/apps/${APP_NAME}/.next/static /base/apps/${APP_NAME}/.next/static
COPY --from=builder --chown=nextjs:nodejs /base/apps/${APP_NAME}/public /base/apps/${APP_NAME}/public

...

# Start the app.
CMD ["node", "server.js"]

```
Note: The contents of the standalone directory are copied to `/base/`. (My base directory is `base` rather than `app` because I don't like the look of `/app/apps`.)

**Comment by belgattitude** [comment]
Happy to know that it's useful, thanks.

> The contents of the standalone directory are copied to /base/. (My base directory is base rather than app because I don't like the look of /app/apps.)

Yes I agree :smile: 

And yesy it should work. A question about the `.next` folder, isn't that safer to add it to dockerignore ? 

In the short term I'll release rewrite a v2 of this repo... [based on pnpm](https://github.com/belgattitude/nextjs-monorepo-example/pull/2765) - with nx and turbo for the example part. When ready 'll improve the docker too and take the standalone from your example if you don't mind

Thanks again

**Comment by iacobfred** [comment]
> A question about the `.next` folder, isn't that safer to add it to dockerignore ?

Yep, the `.next` folder should be in `.dockerignore`.

> In the short term I'll release rewrite a v2 of this repo... https://github.com/belgattitude/nextjs-monorepo-example/pull/2765 - with nx and turbo for the example part. When ready 'll improve the docker too and take the standalone from your example if you don't mind

Awesome. Looking forward to seeing your v2.

**Comment by belgattitude** [comment]
Closed as it’s done in https://github.com/belgattitude/nextjs-monorepo-example/blob/main/docker/Dockerfile
