### ISSUE TITLE
changeset publish does not replace workspace: ranges with current version in workspace

### ISSUE THREAD

**Issue by tianyingchun** [belgattitude/nextjs-monorepo-example#2821]
it seems that github action auto publish dont work: https://github.com/changesets/changesets/pull/674

could you explain how to make publish works correctly? what configuration need ?

**Comment by belgattitude** [comment]
You can have a look to https://github.com/soluble-io/cache-interop/blob/cae989e6f73053bc532b1b6ea68dcf185edd581e/packages/cache-ioredis/package.json#L44

**Comment by tianyingchun** [comment]
have you try `"@changesets/cli": "2.22.0-temp.0",`?

try using @changesets/cli@2.22.0-temp.0 publish failed.
using @changesets/cli@2.25.0 it works, but package dependencies wrong keep :workpsace:^
➤ YN0000: Done in 7s 668ms
🦋 info npm info @armit/cli
🦋 info npm info @armit/common
🦋 info npm info @armit/eslint-config-bases
🦋 info @armit/cli is being published because our local version (0.0.5) has not been published on npm
🦋 info @armit/common is being published because our local version (0.0.5) has not been published on npm
🦋 info @armit/eslint-config-bases is being published because our local version (0.0.4) has not been published on npm
🦋 info Publishing "@armit/cli" at "0.0.5"
🦋 info Publishing "@armit/common" at "0.0.5"
🦋 info Publishing "@armit/eslint-config-bases" at "0.0.4"
🦋 error an error occurred while publishing @armit/eslint-config-bases:
🦋 error ➤ YN0000: CHANGELOG.md
🦋 error ➤ YN0000: README.md
🦋 error ➤ YN0000: package.json
🦋 error ➤ YN0000: src/bases/index.js
🦋 error ➤ YN0000: src/bases/jest.js
🦋 error ➤ YN0000: src/bases/playwright.js
🦋 error ➤ YN0000: src/bases/prettier.js
🦋 error ➤ YN0000: src/bases/react.js
🦋 error ➤ YN0000: src/bases/regexp.js
🦋 error ➤ YN0000: src/bases/rtl.js
🦋 error ➤ YN0000: src/bases/sonar.js
🦋 error ➤ YN0000: src/bases/storybook.js
🦋 error ➤ YN0000: src/bases/tailwind.js
🦋 error ➤ YN0000: src/bases/typescript.js
🦋 error ➤ YN0000: src/bases/vitest.js
🦋 error ➤ YN0000: src/helpers/getDefaultIgnorePatterns.js
🦋 error ➤ YN0000: src/helpers/getPrettierConfig.js
🦋 error ➤ YN0000: src/helpers/index.js
🦋 error ➤ YN0000: src/index.js
🦋 error ➤ YN0000: src/patch/modern-module-resolution.js
🦋 error ➤ YN0000: src/prettier.base.config.js
🦋 error ➤ YN0033: No authentication configured for request
🦋 error an error occurred while publishing @armit/cli:
🦋 error ➤ YN0000: CHANGELOG.md
🦋 error ➤ YN0000: LICENSE
🦋 error ➤ YN0000: README.md
🦋 error ➤ YN0000: bin/armit.mjs
🦋 error ➤ YN0000: dist/index.d.ts
🦋 error ➤ YN0000: dist/index.js
🦋 error ➤ YN0000: dist/index.js.map
🦋 error ➤ YN0000: index.js
🦋 error ➤ YN0000: package.json
🦋 error ➤ YN0033: No authentication configured for request
🦋 error an error occurred while publishing @armit/common:
🦋 error ➤ YN0000: CHANGELOG.md
🦋 error ➤ YN0000: LICENSE
🦋 error ➤ YN0000: README.md
🦋 error ➤ YN0000: dist/index.d.ts
🦋 error ➤ YN0000: dist/index.js
🦋 error ➤ YN0000: dist/index.js.map
🦋 error ➤ YN0000: index.js
🦋 error ➤ YN0000: package.json
🦋 error ➤ YN0033: No authentication configured for request
🦋 error packages failed to publish:
🦋 @armit/cli@0.0.5
🦋 @armit/common@0.0.5
🦋 @armit/eslint-config-bases@0.0.4
Error: The process '/usr/local/bin/yarn' failed with exit code 1
at m._setResult (/home/runner/work/_actions/changesets/action/v1/dist/index.js:102:7258)
Error: The process '/usr/local/bin/yarn' failed with exit code 1
at m.CheckComplete (/home/runner/work/_actions/changesets/action/v1/dist/index.js:102:[66](https://github.com/armitjs/armit/actions/runs/3301463560/jobs/5446958342#step:5:67)86)
at ChildProcess. (/home/runner/work/_actions/changesets/action/v1/dist/index.js:102:5[72](https://github.com/armitjs/armit/actions/runs/3301463560/jobs/5446958342#step:5:73)3)
at ChildProcess.emit (events.js:314:20)
at maybeClose (internal/child_process.js:1022:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:2[87](https://github.com/armitjs/armit/actions/runs/3301463560/jobs/5446958342#step:5:88):5)

**Comment by tianyingchun** [comment]
it seems that need configuration `yarn npm publish token`? if so how to config this in `CI`

**Comment by belgattitude** [comment]
Please keep the issue reporting on the changesets repo. 

Or looks closely to the links I've provided above,  theycontain the solution and works.
