### ISSUE TITLE
Semantic error TS6059 File 'packages/ts-utils/src/index.ts' is not under 'rootDir'

### ISSUE THREAD

**Issue by marie-maxime** [belgattitude/nextjs-monorepo-example#3249]
Hello, I am getting this error when trying to build with `yarn g:build` locally.

```
semantic error TS6059: File '/Users/marie-maxime/webdev/nextjs-monorepo-example/packages/ts-utils/src/index.ts' is not under 'rootDir' '/Users/marie-maxime/webdev/nextjs-monorepo-example/packages/ui-lib/src'. 'rootDir' is expected to contain all source files.
```

To reproduce:

In file `nextjs-monorepo-example/packages/ui-lib/src/base/index.ts` 
add the following line `export { BasicCard } from './card/BasicCard';`
and then run `yarn g:build` in root folder.

This seems to be caused by `import { isNonEmptyString } from '@your-org/ts-utils';`

Tested with a fresh install and  latest version of main as of time of writing this issue.

Thank you for building and maintaining this repo btw!

**Comment by belgattitude** [comment]
Hi @marie-maxime, thanks for reporting. 

I wasn't able to reproduce it yet, but it might related to a specific os/node version ?

Could you run 

```bash
npx envinfo --binaries --monorepos --system
```

And paste the output ?

On my side I have this:

```
  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 8.20 GB / 15.29 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 4.0.0-rc.37 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Monorepos:
    Yarn Workspaces: 4.0.0-rc.37
```

PS: I've updated typescript 4.9.5 part of  https://github.com/belgattitude/nextjs-monorepo-example/pull/3259 (might be related ?)

If you want you can always check the installed dep versions with `yarn deps:check`  (and `ỳarn deps:update && yarn install && yarn dedupe` to apply on your side) .

**Comment by marie-maxime** [comment]
Hmm, that's weird, I just tried spinning a new instance in Github codespace and still having the issue when I add the export statement for BasicCard.

Upgrading packages doesn't seems to fix the issue either.

My laptop:
```
  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 116.06 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 4.0.0-rc.37 - /usr/local/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
```

Codespace:
```
  System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 1.76 GB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 19.5.0 - ~/nvm/current/bin/node
    Yarn: 4.0.0-rc.37 - /usr/bin/yarn
    npm: 9.3.1 - ~/nvm/current/bin/npm
  Monorepos:
    Yarn Workspaces: 4.0.0-rc.37
```

**Comment by belgattitude** [comment]
@marie-maxime  I've swapped two issues in my mind, and actually haven't replied to yours :smile: 

Happens sometimes. Of course you're totally right, it does not work.

So here's a fix: https://github.com/belgattitude/nextjs-monorepo-example/pull/3264 with an explanation.

This repo is just a collection of tools together, but if you're wanting to build a design-system for real, I recommend to build with rollup (v3).... tsup is nice to start. microbundle too but does not play super well with aliases
