### ISSUE TITLE
storybook recognizing tailwind config from outside 

### ISSUE THREAD

**Issue by TheMikeyRoss** [belgattitude/nextjs-monorepo-example#4883]
Hi, 

I have a ui kit library and im migrating to a monorepo structure [here](https://github.com/sikka-software/Hawa/tree/monorepo)

My structure is similar to the one here
├── apps
│   ├── docs  (next.js app)
└── packages
    ├── components        (the actual ui kit)
    ├── storybook 

And the storybook workspace is used to develop the ui components from the `componenets` workspace. But for some reason storybook is not able to recognize the tailwind.config.js from `/components` workspace

**Comment by belgattitude** [comment]
On my phone for few days… by intuition check the tailwind config in the storybook package to ensure that the content key includes a relative path to the components source. Ie ../components/src/**/*.tsx

That should ensure that tailwind / postcss is able to scan for the used classnames and extract them properly. 

let me know if it helps and congrats for your project.

**Comment by belgattitude** [comment]
Adding a small advice… I feel it’s easier to install storybook inside of the component package. That way you can collocate your stories files closer to their actual components.

**Comment by TheMikeyRoss** [comment]
> by intuition check the tailwind config in the storybook package to ensure that the content key includes a relative path to the components source. Ie ../components/src/**/*.tsx

OMG thank you so much that solved it! I've been digging deep for 3 days thinking the problem is with storybook compiling postcss

THANK YOU SO MUCH!!! ♥♥
