### ISSUE TITLE
Parsing error: Cannot read file '/monorepo/tsconfig.json' eslint error in VS Code

### ISSUE THREAD

**Issue by oste** [belgattitude/nextjs-monorepo-example#687]
I think it might be worth adding a note regarding VS Code eslint extension workingDirectories setting. More info here https://github.com/microsoft/vscode-eslint#mono-repository-setup

Adding this to the VS Code settings resolves the error.
```
    "eslint.workingDirectories": [
        {
            "pattern": "./apps/*/"
        },
        {
            "pattern": "./packages/*/"
        }
    ],
```

**Comment by belgattitude** [comment]
Hey @oste, thanks a lot.

I'm actually on Jetbrains product line, would you mind adding a P/R to the repo ?

Would be awesome

**Comment by oste** [comment]
Certainly. Let me know how this looks https://github.com/belgattitude/nextjs-monorepo-example/pull/737

**Comment by belgattitude** [comment]
I merged https://github.com/belgattitude/nextjs-monorepo-example/pull/737, so I'll close.

Thank you

**Comment by ekafyi** [comment]
Sorry for bumping—posting this for others who might be searching this issue.

I had similar issue; adding VSCode settings did not work; solved by updating each package's eslint config, eg. `/apps/blog-app/.eslintrc.js`.

```diff
module.exports = {
+  parserOptions: {
+    tsconfigRootDir: __dirname,
+    project: ['./apps/*/tsconfig.json', './packages/*/tsconfig.json'],
+  },
}
```

Copy-pasted from https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/MONOREPO.md#one-tsconfigjson-per-package-and-an-optional-one-in-the-root

`yarn lint` is not affected by all these, seems to be a VSCode + eslint extension issue.
