### ISSUE TITLE
Parsing error: Unknown compiler option 'useUnknownInCatchVariables'.eslint

### ISSUE THREAD

**Issue by oste** [belgattitude/nextjs-monorepo-example#688]
This one seems related to my specific typescript version. By all accounts it seems to be 4.4.4 which should support this flag. I have disabled `"useUnknownInCatchVariables": true,` from my tsconfig.base.json as a fix for now and will try to circle back on what happened here.

**Comment by belgattitude** [comment]
That's weird. Is the error reported by vscode ?

Asking because, I haven't had this issue on my part (neither on the ci).

Can you run a typecheck from the command-line ?

```bash
yarn typecheck
```

> PS:  that assumes all your apps / packages have a typecheck script, see examples.

Another trick, try

```bash
yarn why typescript
```

That way you'll see if you have an older typescript version somewhere.

**Comment by oste** [comment]
oddly enough I can't run `yarn typecheck` I get
```
Unknown Syntax Error: Command not found; did you mean:
...
```

yarn why typescript only shows version 4.3.2+

🤔

**Comment by belgattitude** [comment]
> oddly enough I can't run yarn typecheck I get

It's a custom script.

You can add it to each package.json in apps / packages, ie [here](https://github.com/belgattitude/nextjs-monorepo-example/blob/15068a120cb53d826bcfba7db5f5b26a0d2f0063/apps/web-app/package.json#L44).

```json
"scripts": {
  "typecheck": "tsc --project ./tsconfig.json --noEmit"
}
```

You can run all at at once, by typing `yarn workspaces foreach -ptv run typecheck` or create a global script like this [one](https://github.com/belgattitude/nextjs-monorepo-example/blob/15068a120cb53d826bcfba7db5f5b26a0d2f0063/package.json#L35).

> yarn why typescript only shows version 4.3.2+

Is there multiple lines, multiple version in the output ? This looks weird, I guess you've checked your packages.json...

**Comment by oste** [comment]
I should have mentioned that I do have a similar root package.json with `"typecheck": "yarn workspaces foreach -ptv run typecheck",` and I did add the typecheck script to all workspaces as well.

After further checks I did not have the plugins added to .yarnrc.yml so adding this 

```
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
```

shows this output 
```
➜  monorepo git:(main) ✗ yarn workspaces foreach -ptv run typecheck
➤ YN0000: [nextjs-monorepo-example]: Process started
➤ YN0000: [@your-org/magnificent-poney]: Process started
➤ YN0000: [@your-org/magnificent-poney]: Process exited (exit code 0), completed in 2s 967ms
➤ YN0000: [nextjs-monorepo-example]: ➤ YN0000: [@your-org/magnificent-poney]: Process started
➤ YN0000: [nextjs-monorepo-example]: ➤ YN0000: [@your-org/magnificent-poney]: Process exited (exit code 0), completed in 2s 473ms
```

I do show multiple versions when running `yarn why typescript` but my apps and packages package.json seem to be fine and pointing to version 4.4.4

**Comment by oste** [comment]
it seems this fixed itself! I added `useUnknownInCatchVariables` back to my base tsconfig and I am not getting any eslint errors. I wonder if maybe it was a glitch on vscodes end or if maybe I had a bad install by running yarn install in workspace roots instead of the project root.

I will close this for now.

**Comment by oste** [comment]
I have to reopen b/c I am now noticing `yarn typecheck` gives: 

```
➜  monorepo git:(main) ✗ yarn typecheck
➤ YN0000: [@your-org/magnificent-poney]: Process started
➤ YN0000: [@your-org/magnificent-poney]: ../../tsconfig.base.json(4,5): error TS5023: Unknown compiler option 'useUnknownInCatchVariables'.
➤ YN0000: [@your-org/magnificent-poney]: Process exited (exit code 1), completed in 2s 385ms
➤ YN0000: The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
➤ YN0000: Failed with errors in 2s 393ms
```

**Comment by oste** [comment]
This seems to be a difference between `yarn typecheck` command and directly running `yarn workspaces foreach -ptv run typecheck`

The former shows the Unknown compiler option error. The second one seems to get by without issue.

**Comment by belgattitude** [comment]
Really looks likeyou still have an older typescript version in the magnificent poney package.

Can you paste the result of yarn why typescript ?

**Comment by belgattitude** [comment]
Side-note, it might be in your yarn.lock from a previous install, if possible try out `yarn dedupe` on the top level
