### ISSUE TITLE
Yarn3 PnP Jest Issue

### ISSUE THREAD

**Issue by jwangtacit** [belgattitude/nextjs-monorepo-example#800]
I tried `yarn test` & `yarn workspace web-app test` in the `yarn-pnp` branch, and got these errors.

- yarn test
```
➤ YN0000: [@your-org/core-lib]: Process started
➤ YN0000: [@your-org/ui-lib]: Process started
➤ YN0000: [@your-org/ui-lib]: No tests yet
➤ YN0000: [@your-org/ui-lib]: Process exited (exit code 0), completed in 0s 443ms
➤ YN0000: [@your-org/core-lib]: ● Validation Error:
➤ YN0000: [@your-org/core-lib]: 
➤ YN0000: [@your-org/core-lib]:   Module jest-circus/runner in the testRunner option was not found.
➤ YN0000: [@your-org/core-lib]:          <rootDir> is: /Users/jackjin/Documents/nextjs-monorepo-example/packages/core-lib/src
➤ YN0000: [@your-org/core-lib]: 
➤ YN0000: [@your-org/core-lib]:   Configuration Documentation:
➤ YN0000: [@your-org/core-lib]:   https://jestjs.io/docs/configuration
➤ YN0000: [@your-org/core-lib]: 
➤ YN0000: [@your-org/core-lib]: Process exited (exit code 1), completed in 0s 770ms
➤ YN0000: The command failed for workspaces that are depended upon by other workspaces; can't satisfy the dependency graph
➤ YN0000: Failed with errors in 0s 776ms
ERROR: "test:unit" exited with 1.
```

- yarn workspace web-app test
```
● Validation Error:

  Module jest-circus/runner in the testRunner option was not found.
         <rootDir> is: /Users/jackjin/Documents/nextjs-monorepo-example/apps/web-app/src

  Configuration Documentation:
  https://jestjs.io/docs/configuration

ERROR: "test:unit" exited with 1.
```

Yarn: 3.0.0-rc6
Node: 14.17.0
OS: MacOS 11.3

**Comment by belgattitude** [comment]
I haven't put energy in pnp for few reasons. 

- things like prisma did not support it when I tested them
- the deployments with vercel,  serverless... and the way node tracing (vercel/nft) works to remove unused files seems only effective with a classic node_modules install

So I haven't invested too much time in this area. Pnp is super nice though,  and I can make it work in different contexts (with some effort though)

So my 2 cents,  check the yarnrc.yml in this repo to see how to enable node module linker. And try to keep your yarn version to latest (yarn set version 3.1.0, yarn plugin import workspace-tools...). This will give the easiest way to work

There's an old branch branch for pnp support in this repo also, but I haven't continued.  

But if you find a way to make it work let me know, would be great.

**Comment by belgattitude** [comment]
Hey @jwangtacit I did a quick attempt with updated stack here: https://github.com/belgattitude/nextjs-monorepo-example/pull/864

A lot of things breaks like husky, lint-staged... I could make prisma work though. 

But I still think it's not prime time.

I'll close this issue feel free to re-open it and provide a P/R if you feel so.
